name: flip_clock_pomodoro
description: "复古翻页时钟 + 番茄计时器"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  # 降级音频插件，规避Embedding V2强制升级要求
  audioplayers: ^5.2.1
  provider: ^6.0.5
  # 暂时移除通知插件，先保证打包成功，后续你可以单独适配
  # flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
